FROM node:14

RUN echo "deb http://packages.cloud.google.com/apt gcsfuse-stretch main" | tee /etc/apt/sources.list.d/gcsfuse.list \
&& curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - \
&& apt-get update && apt-get -y install gcsfuse

WORKDIR /usr/src/app

COPY package*.json ./


RUN npm install

COPY . .

CMD [ "node", "app-jobsrv.js", "dev" ]